#!/usr/bin/env bash

SERVICE_PLATFORM=launchd
LAUNCHCTL_BIN="${LAUNCHCTL_BIN:-launchctl}"
USER_ID="${USER_ID:-$(id -u)}"
LAUNCHD_LABEL="com.rclipboard.service"
LAUNCHD_DOMAIN="gui/$USER_ID"
LAUNCHD_DIR="$HOME/Library/LaunchAgents"
LAUNCHD_PLIST="$LAUNCHD_DIR/$LAUNCHD_LABEL.plist"
LAUNCHD_MARKER="<!-- Generated by rclipboard installer -->"

LAUNCHD_ADAPTER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAUNCHD_TEMPLATE="$LAUNCHD_ADAPTER_DIR/../launchd/$LAUNCHD_LABEL.plist.in"
LAUNCHD_LOG_DIR="$HOME/Library/Logs/rclipboard"

launchd_gui_available() {
    "$LAUNCHCTL_BIN" print "$LAUNCHD_DOMAIN" >/dev/null 2>&1
}

service_preflight() {
    check_managed_file_collision "$LAUNCHD_PLIST" "$LAUNCHD_MARKER" \
        || return 1
}

render_launchd_plist() {
    local temporary="${LAUNCHD_PLIST}.render.$$"

    render_xml_template \
        "$LAUNCHD_TEMPLATE" "$temporary" \
        "@SERVICE_RUNNER_XML@" "$APP_DIR/bin/rclipboard-service-run" \
        || return 1
    render_xml_template \
        "$temporary" "$temporary" \
        "@APP_DIR_XML@" "$APP_DIR" \
        || {
            rm -f "$temporary"
            return 1
        }
    render_xml_template \
        "$temporary" "$temporary" \
        "@STDOUT_LOG_XML@" "$LAUNCHD_LOG_DIR/stdout.log" \
        || {
            rm -f "$temporary"
            return 1
        }
    render_xml_template \
        "$temporary" "$temporary" \
        "@STDERR_LOG_XML@" "$LAUNCHD_LOG_DIR/stderr.log" \
        || {
            rm -f "$temporary"
            return 1
        }
    mv -f "$temporary" "$LAUNCHD_PLIST" || {
        rm -f "$temporary"
        return 1
    }
}

service_install() {
    service_preflight || return 1
    mkdir -p "$LAUNCHD_DIR" "$LAUNCHD_LOG_DIR" || return 1
    render_launchd_plist || return 1
}

service_start() {
    if launchd_gui_available; then
        "$LAUNCHCTL_BIN" bootout "$LAUNCHD_DOMAIN" "$LAUNCHD_PLIST" \
            >/dev/null 2>&1 || true
        "$LAUNCHCTL_BIN" bootstrap "$LAUNCHD_DOMAIN" "$LAUNCHD_PLIST" \
            || return 1
    else
        warn "LaunchAgent installed; it will load at the next graphical login"
    fi
}

service_stop() {
    "$LAUNCHCTL_BIN" bootout "$LAUNCHD_DOMAIN" "$LAUNCHD_PLIST" \
        >/dev/null 2>&1 || true
}

service_restart() {
    if launchd_gui_available; then
        "$LAUNCHCTL_BIN" kickstart -k "$LAUNCHD_DOMAIN/$LAUNCHD_LABEL" \
            || return 1
    else
        warn "LaunchAgent is unavailable outside a graphical login session"
    fi
}

service_uninstall() {
    service_stop
    remove_marked_file "$LAUNCHD_PLIST" "$LAUNCHD_MARKER" || return 1
}
