#!/usr/bin/env bash

SERVICE_PLATFORM=launchd
LAUNCHCTL_BIN="${LAUNCHCTL_BIN:-launchctl}"
USER_ID="${USER_ID:-$(id -u)}"
LAUNCHD_LABEL="com.rclipboard.service"
LAUNCHD_DOMAIN="gui/$USER_ID"
LAUNCHD_DIR="$HOME/Library/LaunchAgents"
LAUNCHD_PLIST="$LAUNCHD_DIR/$LAUNCHD_LABEL.plist"
LAUNCHD_MARKER="<!-- Generated by rclipboard installer -->"
# launchctl reports an absent service as POSIX ESRCH (No such process).
LAUNCHD_NOT_LOADED_STATUS=3
# `launchctl print gui/<uid>` reports a missing login domain with this status.
LAUNCHD_GUI_UNAVAILABLE_STATUS=113

LAUNCHD_ADAPTER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAUNCHD_TEMPLATE="$LAUNCHD_ADAPTER_DIR/../launchd/$LAUNCHD_LABEL.plist.in"
LAUNCHD_LOG_DIR="$HOME/Library/Logs/rclipboard"

launchd_gui_available() {
    local output status

    if output=$("$LAUNCHCTL_BIN" print "$LAUNCHD_DOMAIN" 2>&1); then
        return 0
    else
        status=$?
    fi
    if [ "$status" -eq "$LAUNCHD_GUI_UNAVAILABLE_STATUS" ]; then
        return "$LAUNCHD_GUI_UNAVAILABLE_STATUS"
    fi
    case "$output" in
        *"Could not find domain"*|*"Could not find service \"$LAUNCHD_DOMAIN\""*)
            return "$LAUNCHD_GUI_UNAVAILABLE_STATUS"
            ;;
    esac
    [ -z "$output" ] || printf '%s\n' "$output" >&2
    return "$status"
}

service_preflight() {
    check_managed_file_collision "$LAUNCHD_PLIST" "$LAUNCHD_MARKER" xml \
        || return 1
}

launchd_bootout_plist() {
    local output status

    if output=$("$LAUNCHCTL_BIN" bootout \
        "$LAUNCHD_DOMAIN" "$LAUNCHD_PLIST" 2>&1); then
        return 0
    else
        status=$?
    fi
    if [ "$status" -eq "$LAUNCHD_NOT_LOADED_STATUS" ]; then
        return 0
    fi
    [ -z "$output" ] || printf '%s\n' "$output" >&2
    return "$status"
}

render_launchd_plist() {
    local temporary="${LAUNCHD_PLIST}.render.$$"

    render_xml_template \
        "$LAUNCHD_TEMPLATE" "$temporary" \
        "@SERVICE_RUNNER_XML@" "$APP_DIR/bin/rclipboard-service-run" \
        || return 1
    render_xml_template \
        "$temporary" "$temporary" \
        "@APP_DIR_XML@" "$APP_DIR" \
        || {
            rm -f "$temporary"
            return 1
        }
    render_xml_template \
        "$temporary" "$temporary" \
        "@STDOUT_LOG_XML@" "$LAUNCHD_LOG_DIR/stdout.log" \
        || {
            rm -f "$temporary"
            return 1
        }
    render_xml_template \
        "$temporary" "$temporary" \
        "@STDERR_LOG_XML@" "$LAUNCHD_LOG_DIR/stderr.log" \
        || {
            rm -f "$temporary"
            return 1
        }
    mv -f "$temporary" "$LAUNCHD_PLIST" || {
        rm -f "$temporary"
        return 1
    }
}

service_install() {
    service_preflight || return 1
    mkdir -p "$LAUNCHD_DIR" "$LAUNCHD_LOG_DIR" || return 1
    render_launchd_plist || return 1
}

service_start() {
    local status

    if launchd_gui_available; then
        launchd_bootout_plist || return $?
        "$LAUNCHCTL_BIN" bootstrap "$LAUNCHD_DOMAIN" "$LAUNCHD_PLIST" \
            || return 1
    else
        status=$?
        [ "$status" -eq "$LAUNCHD_GUI_UNAVAILABLE_STATUS" ] \
            || return "$status"
        warn "LaunchAgent installed; it will load at the next graphical login"
    fi
}

service_print_status_hint() {
    printf '  Status:   launchctl print gui/%s/%s\n' \
        "$USER_ID" "$LAUNCHD_LABEL"
}

service_stop() {
    launchd_bootout_plist || return $?
}

service_restart() {
    local status

    if launchd_gui_available; then
        "$LAUNCHCTL_BIN" kickstart -k "$LAUNCHD_DOMAIN/$LAUNCHD_LABEL" \
            || return 1
    else
        status=$?
        [ "$status" -eq "$LAUNCHD_GUI_UNAVAILABLE_STATUS" ] \
            || return "$status"
        warn "LaunchAgent is unavailable outside a graphical login session"
    fi
}

service_uninstall() {
    managed_file_has_marker "$LAUNCHD_PLIST" "$LAUNCHD_MARKER" xml \
        || return 0
    service_stop || return $?
    remove_marked_file "$LAUNCHD_PLIST" "$LAUNCHD_MARKER" xml || return 1
}
