#!/usr/bin/env bash

SERVICE_PLATFORM=systemd
SYSTEMCTL_BIN="${SYSTEMCTL_BIN:-systemctl}"
SYSTEMD_UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
SYSTEMD_MARKER="# Generated by rclipboard installer"

SYSTEMD_ADAPTER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYSTEMD_TEMPLATE_DIR="$SYSTEMD_ADAPTER_DIR/../systemd/user"

service_preflight() {
    check_managed_file_collision \
        "$SYSTEMD_UNIT_DIR/rclipboard.service" "$SYSTEMD_MARKER"
    check_managed_file_collision \
        "$SYSTEMD_UNIT_DIR/rclipboard-display.service" "$SYSTEMD_MARKER"
}

service_install() {
    service_preflight
    mkdir -p "$SYSTEMD_UNIT_DIR"
    render_template \
        "$SYSTEMD_TEMPLATE_DIR/rclipboard.service" \
        "$SYSTEMD_UNIT_DIR/rclipboard.service" \
        "@APP_DIR@" "$APP_DIR"
    render_template \
        "$SYSTEMD_TEMPLATE_DIR/rclipboard-display.service" \
        "$SYSTEMD_UNIT_DIR/rclipboard-display.service" \
        "@APP_DIR@" "$APP_DIR"
    "$SYSTEMCTL_BIN" --user daemon-reload
}

service_start() {
    "$SYSTEMCTL_BIN" --user enable --now rclipboard.service
    if "$APP_DIR/venv/bin/rclipboard" config env \
        --config "$CONFIG_DIR/config.toml" \
        | grep -Fqx 'RCLIPBOARD_XSEL="1"'; then
        "$SYSTEMCTL_BIN" --user enable --now rclipboard-display.service
    fi
}

service_stop() {
    "$SYSTEMCTL_BIN" --user disable --now rclipboard-display.service \
        >/dev/null 2>&1 || true
    "$SYSTEMCTL_BIN" --user disable --now rclipboard.service \
        >/dev/null 2>&1 || true
}

service_restart() {
    "$SYSTEMCTL_BIN" --user restart rclipboard.service
}

remove_legacy_systemd_dropin() {
    local dropin_dir="$SYSTEMD_UNIT_DIR/rclipboard.service.d"
    local override="$dropin_dir/override.conf"
    local content expected

    [ -f "$override" ] && [ ! -L "$override" ] || return 0
    content=$(cat "$override")
    expected="[Service]
WorkingDirectory=$APP_DIR"
    if [ "$content" = "$expected" ]; then
        rm -f "$override"
        rmdir "$dropin_dir" 2>/dev/null || true
    fi
}

service_uninstall() {
    service_stop
    remove_marked_file \
        "$SYSTEMD_UNIT_DIR/rclipboard-display.service" "$SYSTEMD_MARKER"
    remove_marked_file \
        "$SYSTEMD_UNIT_DIR/rclipboard.service" "$SYSTEMD_MARKER"
    remove_legacy_systemd_dropin
    "$SYSTEMCTL_BIN" --user daemon-reload
}
