#!/usr/bin/env bash

SERVICE_PLATFORM=systemd
SYSTEMCTL_BIN="${SYSTEMCTL_BIN:-systemctl}"
SYSTEMD_UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
SYSTEMD_MARKER="# Generated by rclipboard installer"

SYSTEMD_ADAPTER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYSTEMD_TEMPLATE_DIR="$SYSTEMD_ADAPTER_DIR/../systemd/user"

service_preflight() {
    check_managed_file_collision \
        "$SYSTEMD_UNIT_DIR/rclipboard.service" "$SYSTEMD_MARKER" || return 1
    check_managed_file_collision \
        "$SYSTEMD_UNIT_DIR/rclipboard-display.service" "$SYSTEMD_MARKER" \
        || return 1
}

service_install() {
    service_preflight || return 1
    mkdir -p "$SYSTEMD_UNIT_DIR" || return 1
    render_template \
        "$SYSTEMD_TEMPLATE_DIR/rclipboard.service" \
        "$SYSTEMD_UNIT_DIR/rclipboard.service" \
        "@APP_DIR@" "$APP_DIR" || return 1
    render_template \
        "$SYSTEMD_TEMPLATE_DIR/rclipboard-display.service" \
        "$SYSTEMD_UNIT_DIR/rclipboard-display.service" \
        "@APP_DIR@" "$APP_DIR" || return 1
    "$SYSTEMCTL_BIN" --user daemon-reload || return 1
}

service_start() {
    "$SYSTEMCTL_BIN" --user enable --now rclipboard.service || return 1
    if "$APP_DIR/venv/bin/rclipboard" config env \
        --config "$CONFIG_DIR/config.toml" \
        | grep -Fqx 'RCLIPBOARD_XSEL="1"'; then
        "$SYSTEMCTL_BIN" --user enable --now rclipboard-display.service
    fi
}

service_print_status_hint() {
    printf '  Status:   systemctl --user status rclipboard.service\n'
}

service_stop() {
    "$SYSTEMCTL_BIN" --user disable --now rclipboard-display.service \
        >/dev/null 2>&1 || true
    "$SYSTEMCTL_BIN" --user disable --now rclipboard.service \
        >/dev/null 2>&1 || true
}

service_restart() {
    "$SYSTEMCTL_BIN" --user restart rclipboard.service
}

remove_legacy_systemd_dropin() {
    local dropin_dir="$SYSTEMD_UNIT_DIR/rclipboard.service.d"
    local override="$dropin_dir/override.conf"
    local content expected

    [ -f "$override" ] && [ ! -L "$override" ] || return 0
    content=$(cat "$override") || return 1
    expected="[Service]
WorkingDirectory=$APP_DIR"
    if [ "$content" = "$expected" ]; then
        rm -f "$override" || return 1
        SYSTEMD_UNINSTALL_CHANGED=1
        rmdir "$dropin_dir" 2>/dev/null || true
    fi
}

uninstall_owned_systemd_unit() {
    local path="$1" unit="$2"

    managed_file_has_marker "$path" "$SYSTEMD_MARKER" || return 0
    "$SYSTEMCTL_BIN" --user disable --now "$unit" \
        >/dev/null 2>&1 || return 1
    remove_marked_file "$path" "$SYSTEMD_MARKER" || return 1
    SYSTEMD_UNINSTALL_CHANGED=1
}

service_uninstall() {
    SYSTEMD_UNINSTALL_CHANGED=0
    uninstall_owned_systemd_unit \
        "$SYSTEMD_UNIT_DIR/rclipboard-display.service" \
        rclipboard-display.service || return 1
    uninstall_owned_systemd_unit \
        "$SYSTEMD_UNIT_DIR/rclipboard.service" \
        rclipboard.service || return 1
    remove_legacy_systemd_dropin || return 1
    if [ "$SYSTEMD_UNINSTALL_CHANGED" -eq 1 ]; then
        "$SYSTEMCTL_BIN" --user daemon-reload || return 1
    fi
}
